# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SafariDarkMode' do
pod 'RealmSwift'
end

target 'SafariDarkModeTests' do

end

target 'SafariDarkModeUITests' do

end

